version: 0.2
            
phases:
  install:
    commands:
      - yum install -y zip
      - pip install requests -t .
  build:
    commands:
      - zip -r lambda.zip curlyqueue.py requests
      - zip -r lambda.zip curlyqueue.py urllib3
      - aws lambda update-function-code --function-name ${target_lambda} --zip-file fileb://lambda.zip

artifacts:
  files:
    - lambda.zip
